# Site settings
title: Peaceful Respite
name: Peaceful Respite
author: Brett Chalupa
description: > # this means to ignore newlines until "baseurl:"
  Celebrating Japanese video games. Peaceful Respite is dedicated to
  covering the best Japanese games that get released in the West, from
  recent release to classics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.peacefulrespite.com" # the base hostname & protocol for your site
twitter_username: peacefulrespite
permalink: :title

collections:
  content:
    title: Content
    output: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
