# Site settings
title: Peaceful Respite
name: Peaceful Respite
description: > # this means to ignore newlines until "baseurl:"
  For fans of Japanese video games. Peaceful Respite is dedicated to
  covering the best Japanese games that get released in the West, from
  recent release to classics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.peacefulrespite.com" # the base hostname & protocol for your site
twitter_username: peacefulrespite
permalink: :title

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
